services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bookworm
      POSTGRES_PASSWORD: bookworm
      POSTGRES_DB: bookworm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    build: .
    restart: always
    command: pnpm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  db-data:
